### ISSUE TITLE
Brakes Microsoft teams site

### ISSUE THREAD

**Issue by kessedk** [barbushin/javascript-errors-notifier#79]
If I have javascript-errors-notifier enabled when clicking around my companies teams sites. It causes errors to occur. Disabling the extension resolves the issue.

The errors I see are: 
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at console.window.console.error (<anonymous>:36:101)
    at o (https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:6848)
    at https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:7107
    at a (https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:7113)
    at HTMLAnchorElement.invoke (https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:15423) undefined

or:
TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at console.window.console.error (<anonymous>:36:101)
    at o (https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:6848)
    at https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:7107
    at a (https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:7113)
    at invoke (https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:15423)
    at n.args.(anonymous function) (https://statics.teams.microsoft.com/hashedjs/2-vendor.min-b931c13d.js:293:3908) undefined

Would be great to get it working as it's nice having it while debugging

**Comment by marcin-gryszkalis** [comment]
It seems to break WordPress Gutenberg editor: https://github.com/WordPress/gutenberg/issues/10490
